"""empty message

Revision ID: aa50913ea856
Revises: f127d2bce923
Create Date: 2025-03-14 20:45:08.876015

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aa50913ea856'
down_revision = 'f127d2bce923'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_column('required_specialization')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('required_specialization', mysql.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
